#!/bin/sh

openPrefs() {
  if [ "$(which gnome-extensions)" ]
  then
    gnome-extensions prefs $1
  else
    gdbus call --session \
      --dest=org.gnome.Shell.Extensions \
      --object-path=/org/gnome/Shell/Extensions \
      --method=org.gnome.Shell.Extensions.OpenExtensionPrefs $1 '' '{}'
  fi
}

cat >&2 <<EOT
The gnome-shell-extension-prefs program is deprecated.

Run gnome-extensions-app (from the gnome-shell-extension-prefs package)
for extension management, or use the gnome-extensions command line tool.

Extensions can use the ExtensionUtils.openPrefs() method.
EOT

UUID=$1

if [ "$UUID" ]
then
  openPrefs $UUID
else
  gapplication launch org.gnome.Extensions
fi
